/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author pfsel
 */
public class JPSelecao extends javax.swing.JPanel {
    
    private JFPrincipal pai;

    /**
     * Creates new form JPSelecao
     */
    public JPSelecao(JFPrincipal p) {
        this.pai = p;
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGMonitora = new javax.swing.ButtonGroup();
        bGTipos = new javax.swing.ButtonGroup();
        jBAlerta = new javax.swing.JButton();
        jBRelatorio = new javax.swing.JButton();
        jRBAluno = new javax.swing.JRadioButton();
        jRBTurma = new javax.swing.JRadioButton();
        jRBCurso = new javax.swing.JRadioButton();
        jTFIdentificacao = new javax.swing.JTextField();
        jFTPeriodo1 = new javax.swing.JFormattedTextField();
        jLAux = new javax.swing.JLabel();
        jFTPeriodo2 = new javax.swing.JFormattedTextField();
        jRBFaltasCon = new javax.swing.JRadioButton();
        jRBFaltasInt = new javax.swing.JRadioButton();
        jRBFaltasSem = new javax.swing.JRadioButton();
        jRBChegada = new javax.swing.JRadioButton();
        jRBSaida = new javax.swing.JRadioButton();
        jTFFaltasCon = new javax.swing.JTextField();
        jTFFaltasInt = new javax.swing.JTextField();
        jTFChegadaMin = new javax.swing.JTextField();
        jTFChegadaVezes = new javax.swing.JTextField();
        jTFSaidaMin = new javax.swing.JTextField();
        jTFSaidaVezes = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBExcluirTab = new javax.swing.JButton();
        jlNomeAlerta = new javax.swing.JLabel();
        jTFNomeAlerta = new javax.swing.JTextField();
        jBVoltar = new javax.swing.JButton();
        jBCriar = new javax.swing.JButton();

        jBAlerta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBAlerta.setText("Alerta");

        jBRelatorio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBRelatorio.setText("Relatório");
        jBRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRelatorioActionPerformed(evt);
            }
        });

        bGMonitora.add(jRBAluno);
        jRBAluno.setText("Aluno");
        jRBAluno.setEnabled(false);
        jRBAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAlunoActionPerformed(evt);
            }
        });

        bGMonitora.add(jRBTurma);
        jRBTurma.setText("Turma");
        jRBTurma.setEnabled(false);
        jRBTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBTurmaActionPerformed(evt);
            }
        });

        bGMonitora.add(jRBCurso);
        jRBCurso.setText("Curso");
        jRBCurso.setEnabled(false);
        jRBCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCursoActionPerformed(evt);
            }
        });

        jTFIdentificacao.setForeground(new java.awt.Color(102, 102, 102));
        jTFIdentificacao.setText("INFORME");
        jTFIdentificacao.setEnabled(false);
        jTFIdentificacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFIdentificacaoMouseClicked(evt);
            }
        });
        jTFIdentificacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFIdentificacaoKeyReleased(evt);
            }
        });

        try {
            jFTPeriodo1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTPeriodo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTPeriodo1.setEnabled(false);

        jLAux.setText("à");
        jLAux.setEnabled(false);

        try {
            jFTPeriodo2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTPeriodo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTPeriodo2.setEnabled(false);
        jFTPeriodo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTPeriodo2KeyReleased(evt);
            }
        });

        bGTipos.add(jRBFaltasCon);
        jRBFaltasCon.setText("Faltas consecutivas");
        jRBFaltasCon.setEnabled(false);
        jRBFaltasCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBFaltasConActionPerformed(evt);
            }
        });

        bGTipos.add(jRBFaltasInt);
        jRBFaltasInt.setText("Faltas intercaladas");
        jRBFaltasInt.setEnabled(false);
        jRBFaltasInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBFaltasIntActionPerformed(evt);
            }
        });

        bGTipos.add(jRBFaltasSem);
        jRBFaltasSem.setText("Faltas por dia da semana");
        jRBFaltasSem.setEnabled(false);

        bGTipos.add(jRBChegada);
        jRBChegada.setText("Chegada tardia");
        jRBChegada.setEnabled(false);
        jRBChegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBChegadaActionPerformed(evt);
            }
        });

        bGTipos.add(jRBSaida);
        jRBSaida.setText("Saída antecipada");
        jRBSaida.setEnabled(false);
        jRBSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSaidaActionPerformed(evt);
            }
        });

        jTFFaltasCon.setEnabled(false);
        jTFFaltasCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFFaltasConKeyReleased(evt);
            }
        });

        jTFFaltasInt.setEnabled(false);
        jTFFaltasInt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFFaltasIntKeyReleased(evt);
            }
        });

        jTFChegadaMin.setEnabled(false);
        jTFChegadaMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFChegadaMinKeyReleased(evt);
            }
        });

        jTFChegadaVezes.setEnabled(false);
        jTFChegadaVezes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFChegadaVezesKeyReleased(evt);
            }
        });

        jTFSaidaMin.setEnabled(false);
        jTFSaidaMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFSaidaMinKeyReleased(evt);
            }
        });

        jTFSaidaVezes.setEnabled(false);
        jTFSaidaVezes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFSaidaVezesKeyReleased(evt);
            }
        });

        jPanel1.setEnabled(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alertas"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jBExcluirTab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBExcluirTab.setText("Excluir");
        jBExcluirTab.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jBExcluirTab)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBExcluirTab)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlNomeAlerta.setText("Nome:");
        jlNomeAlerta.setEnabled(false);

        jTFNomeAlerta.setEnabled(false);

        jBVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBVoltar.setText("Voltar");
        jBVoltar.setEnabled(false);
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jBCriar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBCriar.setText("Criar");
        jBCriar.setEnabled(false);
        jBCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCriarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBRelatorio)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBAluno)
                        .addGap(2, 2, 2)
                        .addComponent(jRBTurma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRBCurso))
                    .addComponent(jTFIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFTPeriodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLAux)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTPeriodo2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBFaltasCon)
                        .addGap(38, 38, 38)
                        .addComponent(jTFFaltasCon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBFaltasInt)
                        .addGap(42, 42, 42)
                        .addComponent(jTFFaltasInt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRBFaltasSem)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBChegada)
                            .addComponent(jRBSaida))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFChegadaMin, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jTFSaidaMin))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jlNomeAlerta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFNomeAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFSaidaVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFChegadaVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jBAlerta)
                .addGap(6, 6, 6)
                .addComponent(jBRelatorio)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBAluno)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRBCurso)
                        .addComponent(jRBTurma)))
                .addGap(2, 2, 2)
                .addComponent(jTFIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTPeriodo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLAux)
                    .addComponent(jFTPeriodo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBFaltasCon)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTFFaltasCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBFaltasInt)
                    .addComponent(jTFFaltasInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jRBFaltasSem)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBChegada)
                        .addGap(0, 0, 0)
                        .addComponent(jRBSaida))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFChegadaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFChegadaVezes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFSaidaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFSaidaVezes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeAlerta)
                    .addComponent(jTFNomeAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jBVoltar)
                .addGap(0, 0, 0)
                .addComponent(jBCriar))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRelatorioActionPerformed
        this.jRBAluno.setEnabled(true);
        this.jRBCurso.setEnabled(true);
        this.jRBTurma.setEnabled(true);
        this.jBAlerta.setEnabled(false);
        this.jBVoltar.setEnabled(true);

    }//GEN-LAST:event_jBRelatorioActionPerformed

    private void jRBAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAlunoActionPerformed
        this.jTFIdentificacao.setEnabled(true);
    }//GEN-LAST:event_jRBAlunoActionPerformed

    private void jRBTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBTurmaActionPerformed
        this.jTFIdentificacao.setEnabled(true);
    }//GEN-LAST:event_jRBTurmaActionPerformed

    private void jRBCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCursoActionPerformed
        
        this.jTFIdentificacao.setEnabled(true);
    }//GEN-LAST:event_jRBCursoActionPerformed

    private void jTFIdentificacaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFIdentificacaoKeyReleased
        this.idPreenchido(jTFIdentificacao.getText());

    }//GEN-LAST:event_jTFIdentificacaoKeyReleased

    private void jTFIdentificacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFIdentificacaoMouseClicked
        jTFIdentificacao.setText("");
        jTFIdentificacao.setForeground(Color.BLACK);
    }//GEN-LAST:event_jTFIdentificacaoMouseClicked

    private void jFTPeriodo2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTPeriodo2KeyReleased
        if (this.jTFIdentificacao.getText().length() > 0) {
            this.jRBChegada.setEnabled(true);
            this.jRBFaltasCon.setEnabled(true);
            this.jRBFaltasSem.setEnabled(true);
            this.jRBFaltasInt.setEnabled(true);
            this.jRBSaida.setEnabled(true);
            
        }

    }//GEN-LAST:event_jFTPeriodo2KeyReleased

    private void jRBFaltasConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBFaltasConActionPerformed
        this.verificaTipos();
    }//GEN-LAST:event_jRBFaltasConActionPerformed

    private void jRBFaltasIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBFaltasIntActionPerformed
        this.verificaTipos();

    }//GEN-LAST:event_jRBFaltasIntActionPerformed

    private void jRBChegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBChegadaActionPerformed
        this.verificaTipos();
    }//GEN-LAST:event_jRBChegadaActionPerformed

    private void jTFChegadaMinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFChegadaMinKeyReleased
        if (this.jTFChegadaMin.getText().length() > 0) {
            this.jTFChegadaVezes.setEnabled(true);
        } else {
            this.jTFChegadaVezes.setEnabled(false);
        }

    }//GEN-LAST:event_jTFChegadaMinKeyReleased

    private void jRBSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSaidaActionPerformed
        this.verificaTipos();
    }//GEN-LAST:event_jRBSaidaActionPerformed

    private void jTFSaidaMinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSaidaMinKeyReleased
        if (this.jTFSaidaMin.getText().length() > 0) {
            this.jTFSaidaVezes.setEnabled(true);
        } else {
            this.jTFSaidaVezes.setEnabled(false);
            
        }
    }//GEN-LAST:event_jTFSaidaMinKeyReleased

    private void jBCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCriarActionPerformed
        JOptionPane.showMessageDialog(this, "Relatório será gerado",
                "ATENÇÃO",
                JOptionPane.INFORMATION_MESSAGE);
      this.limpaCampos();

    }//GEN-LAST:event_jBCriarActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
       this.limpaCampos();
       this.jBAlerta.setEnabled(true);
       this.jBRelatorio.setEnabled(true);
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jTFFaltasConKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFFaltasConKeyReleased
      if(this.jTFFaltasCon.getText().length() > 0){
          this.jBCriar.setEnabled(true);
      } else {
          this.jBCriar.setEnabled(false);
      }
    }//GEN-LAST:event_jTFFaltasConKeyReleased

    private void jTFFaltasIntKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFFaltasIntKeyReleased
 if(this.jTFFaltasInt.getText().length() > 0){
          this.jBCriar.setEnabled(true);
      } else {
          this.jBCriar.setEnabled(false);
      }    }//GEN-LAST:event_jTFFaltasIntKeyReleased

    private void jTFChegadaVezesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFChegadaVezesKeyReleased
         if(this.jTFChegadaVezes.getText().length() > 0){
          this.jBCriar.setEnabled(true);
      } else {
          this.jBCriar.setEnabled(false);
      }
    }//GEN-LAST:event_jTFChegadaVezesKeyReleased

    private void jTFSaidaVezesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSaidaVezesKeyReleased
       if(this.jTFSaidaVezes.getText().length() > 0){
          this.jBCriar.setEnabled(true);
      } else {
          this.jBCriar.setEnabled(false);
      }
    }//GEN-LAST:event_jTFSaidaVezesKeyReleased
    
    private void idPreenchido(String texto) {
        if (texto.length() > 0) {
            this.jFTPeriodo1.setEnabled(true);
            this.jFTPeriodo2.setEnabled(true);
            this.jLAux.setEnabled(true);
        } else {
            this.jFTPeriodo1.setEnabled(false);
            this.jFTPeriodo2.setEnabled(false);
            this.jLAux.setEnabled(false);
            this.jRBChegada.setEnabled(false);
            this.jRBFaltasCon.setEnabled(false);
            this.jRBFaltasSem.setEnabled(false);
            this.jRBFaltasInt.setEnabled(false);
            this.jRBSaida.setEnabled(false);
            
        }
        
    }
    
    private void verificaTipos() {
        if (this.jRBFaltasCon.isSelected()) {
            this.jTFFaltasCon.setEnabled(true);
            
        } else {
            this.jTFFaltasCon.setEnabled(false);
            this.jTFFaltasCon.setText("");
        }
        
        if (this.jRBFaltasInt.isSelected()) {
            this.jTFFaltasInt.setEnabled(true);
        } else {
            this.jTFFaltasInt.setEnabled(false);
            this.jTFFaltasInt.setText("");
        }
        
        if (this.jRBChegada.isSelected()) {
            this.jTFChegadaMin.setEnabled(true);
        } else {
            this.jTFChegadaMin.setEnabled(false);
            this.jTFChegadaVezes.setEnabled(false);
            this.jTFChegadaMin.setText("");
            this.jTFChegadaVezes.setText("");
        }
        if (this.jRBSaida.isSelected()) {
            this.jTFSaidaMin.setEnabled(true);
        } else {
            this.jTFSaidaMin.setEnabled(false);
            this.jTFSaidaVezes.setEnabled(false);
            this.jTFSaidaMin.setText("");
            this.jTFSaidaVezes.setText("");
        }
           }
    
    private void limpaCampos(){
        this.jRBAluno.setEnabled(false);
        this.jRBCurso.setEnabled(false);
        this.jRBTurma.setEnabled(false);
        this.bGMonitora.clearSelection();
        this.bGTipos.clearSelection();
        this.jFTPeriodo1.setEnabled(false);
        this.jFTPeriodo2.setEnabled(false);
        this.jLAux.setEnabled(false);
        this.jRBChegada.setEnabled(false);
        this.jRBFaltasCon.setEnabled(false);
        this.jRBFaltasSem.setEnabled(false);
        this.jRBFaltasInt.setEnabled(false);
        this.jRBSaida.setEnabled(false);
        this.jTFIdentificacao.setText("");
        this.jTFIdentificacao.setEnabled(false);
        this.jBCriar.setEnabled(false);
        this.jTFNomeAlerta.setText("");
        this.jTFNomeAlerta.setEnabled(false);
        this.jFTPeriodo1.setText("");
        this.jFTPeriodo2.setText("");
        this.verificaTipos();
        this.jBAlerta.setEnabled(true);
        this.jBRelatorio.setEnabled(true);  
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGMonitora;
    private javax.swing.ButtonGroup bGTipos;
    private javax.swing.JButton jBAlerta;
    private javax.swing.JButton jBCriar;
    private javax.swing.JButton jBExcluirTab;
    private javax.swing.JButton jBRelatorio;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JFormattedTextField jFTPeriodo1;
    private javax.swing.JFormattedTextField jFTPeriodo2;
    private javax.swing.JLabel jLAux;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBAluno;
    private javax.swing.JRadioButton jRBChegada;
    private javax.swing.JRadioButton jRBCurso;
    private javax.swing.JRadioButton jRBFaltasCon;
    private javax.swing.JRadioButton jRBFaltasInt;
    private javax.swing.JRadioButton jRBFaltasSem;
    private javax.swing.JRadioButton jRBSaida;
    private javax.swing.JRadioButton jRBTurma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFChegadaMin;
    private javax.swing.JTextField jTFChegadaVezes;
    private javax.swing.JTextField jTFFaltasCon;
    private javax.swing.JTextField jTFFaltasInt;
    private javax.swing.JTextField jTFIdentificacao;
    private javax.swing.JTextField jTFNomeAlerta;
    private javax.swing.JTextField jTFSaidaMin;
    private javax.swing.JTextField jTFSaidaVezes;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlNomeAlerta;
    // End of variables declaration//GEN-END:variables
}
