/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import bancodedados.Academico;
import bancodedados.Alerta;
import bancodedados.Bancos;
import bancodedados.EscreveAlerta;
import controles.Controle;
import controles.ControleAlerta;
import controles.ControleRelatorio;
import java.awt.Color;
import java.util.Calendar;

/**
 *
 * @author pfsel
 */
public class JPSelecao extends javax.swing.JPanel {

    private JFPrincipal pai;
    private Calendar c1, c2;
    private Controle control;

    // private Bancos d;
    /**
     * Creates new form JPSelecao
     */
    public JPSelecao(JFPrincipal p) {
        this.pai = p;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGMonitora = new javax.swing.ButtonGroup();
        bGTipos = new javax.swing.ButtonGroup();
        jBAlerta = new javax.swing.JButton();
        jBRelatorio = new javax.swing.JButton();
        jRBAluno = new javax.swing.JRadioButton();
        jRBTurma = new javax.swing.JRadioButton();
        jRBCurso = new javax.swing.JRadioButton();
        jTFIdentificacao = new javax.swing.JTextField();
        jFTPeriodo1 = new javax.swing.JFormattedTextField();
        jLAux = new javax.swing.JLabel();
        jFTPeriodo2 = new javax.swing.JFormattedTextField();
        jRBFaltasCon = new javax.swing.JRadioButton();
        jRBFaltasInt = new javax.swing.JRadioButton();
        jRBFaltasSem = new javax.swing.JRadioButton();
        jRBChegada = new javax.swing.JRadioButton();
        jRBSaida = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBExcluirTab = new javax.swing.JButton();
        jlNomeAlerta = new javax.swing.JLabel();
        jTFNomeAlerta = new javax.swing.JTextField();
        jBVoltar = new javax.swing.JButton();
        jBCriar = new javax.swing.JButton();
        jFTFaltasInt = new javax.swing.JFormattedTextField();
        jFTChegadaMin = new javax.swing.JFormattedTextField();
        jFTChegadaVezes = new javax.swing.JFormattedTextField();
        jFTSaidaMin = new javax.swing.JFormattedTextField();
        jFTSaidaVezes = new javax.swing.JFormattedTextField();
        jFTFaltasCon = new javax.swing.JFormattedTextField();
        jTFSemanas = new javax.swing.JTextField();
        jFTSemanasVezes = new javax.swing.JFormattedTextField();
        jBSimulacao = new javax.swing.JButton();

        jBAlerta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBAlerta.setText("Alerta");
        jBAlerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlertaActionPerformed(evt);
            }
        });

        jBRelatorio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBRelatorio.setText("Relatório");
        jBRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRelatorioActionPerformed(evt);
            }
        });

        bGMonitora.add(jRBAluno);
        jRBAluno.setText("Aluno");
        jRBAluno.setEnabled(false);
        jRBAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBAlunoActionPerformed(evt);
            }
        });

        bGMonitora.add(jRBTurma);
        jRBTurma.setText("Turma");
        jRBTurma.setEnabled(false);
        jRBTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBTurmaActionPerformed(evt);
            }
        });

        bGMonitora.add(jRBCurso);
        jRBCurso.setText("Curso");
        jRBCurso.setEnabled(false);
        jRBCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCursoActionPerformed(evt);
            }
        });

        jTFIdentificacao.setForeground(new java.awt.Color(102, 102, 102));
        jTFIdentificacao.setText("INFORME");
        jTFIdentificacao.setEnabled(false);
        jTFIdentificacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFIdentificacaoMouseClicked(evt);
            }
        });
        jTFIdentificacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFIdentificacaoKeyReleased(evt);
            }
        });

        try {
            jFTPeriodo1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTPeriodo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTPeriodo1.setEnabled(false);

        jLAux.setText("à");
        jLAux.setEnabled(false);

        try {
            jFTPeriodo2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTPeriodo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTPeriodo2.setEnabled(false);
        jFTPeriodo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTPeriodo2KeyReleased(evt);
            }
        });

        bGTipos.add(jRBFaltasCon);
        jRBFaltasCon.setText("Faltas consecutivas");
        jRBFaltasCon.setEnabled(false);
        jRBFaltasCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBFaltasConActionPerformed(evt);
            }
        });

        bGTipos.add(jRBFaltasInt);
        jRBFaltasInt.setText("Faltas intercaladas");
        jRBFaltasInt.setEnabled(false);
        jRBFaltasInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBFaltasIntActionPerformed(evt);
            }
        });

        bGTipos.add(jRBFaltasSem);
        jRBFaltasSem.setText("Faltas por dia da semana");
        jRBFaltasSem.setEnabled(false);
        jRBFaltasSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBFaltasSemActionPerformed(evt);
            }
        });

        bGTipos.add(jRBChegada);
        jRBChegada.setText("Chegada tardia");
        jRBChegada.setEnabled(false);
        jRBChegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBChegadaActionPerformed(evt);
            }
        });

        bGTipos.add(jRBSaida);
        jRBSaida.setText("Saída antecipada");
        jRBSaida.setEnabled(false);
        jRBSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSaidaActionPerformed(evt);
            }
        });

        jPanel1.setEnabled(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alertas"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jBExcluirTab.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBExcluirTab.setText("Excluir");
        jBExcluirTab.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jBExcluirTab)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBExcluirTab)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlNomeAlerta.setText("Alerta:");
        jlNomeAlerta.setEnabled(false);

        jTFNomeAlerta.setEnabled(false);
        jTFNomeAlerta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFNomeAlertaKeyReleased(evt);
            }
        });

        jBVoltar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBVoltar.setText("Voltar");
        jBVoltar.setEnabled(false);
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jBCriar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBCriar.setText("Criar");
        jBCriar.setEnabled(false);
        jBCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCriarActionPerformed(evt);
            }
        });

        try {
            jFTFaltasInt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFaltasInt.setEnabled(false);
        jFTFaltasInt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTFaltasIntKeyReleased(evt);
            }
        });

        try {
            jFTChegadaMin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTChegadaMin.setText("");
        jFTChegadaMin.setEnabled(false);
        jFTChegadaMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTChegadaMinKeyReleased(evt);
            }
        });

        try {
            jFTChegadaVezes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTChegadaVezes.setEnabled(false);
        jFTChegadaVezes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTChegadaVezesKeyReleased(evt);
            }
        });

        try {
            jFTSaidaMin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTSaidaMin.setEnabled(false);
        jFTSaidaMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTSaidaMinKeyReleased(evt);
            }
        });

        try {
            jFTSaidaVezes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTSaidaVezes.setEnabled(false);
        jFTSaidaVezes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTSaidaVezesKeyReleased(evt);
            }
        });

        try {
            jFTFaltasCon.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFaltasCon.setEnabled(false);
        jFTFaltasCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTFaltasConKeyReleased(evt);
            }
        });

        jTFSemanas.setForeground(new java.awt.Color(102, 102, 102));
        jTFSemanas.setText("INFORME");
        jTFSemanas.setEnabled(false);
        jTFSemanas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFSemanasMouseClicked(evt);
            }
        });
        jTFSemanas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFSemanasKeyReleased(evt);
            }
        });

        try {
            jFTSemanasVezes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTSemanasVezes.setEnabled(false);
        jFTSemanasVezes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFTSemanasVezesKeyReleased(evt);
            }
        });

        jBSimulacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBSimulacao.setText("Simulação");
        jBSimulacao.setEnabled(false);
        jBSimulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSimulacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jFTChegadaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRBAluno)
                                        .addGap(2, 2, 2)
                                        .addComponent(jRBTurma)
                                        .addGap(2, 2, 2)
                                        .addComponent(jRBCurso))
                                    .addComponent(jTFIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRBFaltasCon)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jFTPeriodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLAux)
                                        .addGap(4, 4, 4)
                                        .addComponent(jFTPeriodo2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jBAlerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jFTSaidaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRBFaltasInt)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFTFaltasCon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFTFaltasInt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBSaida)
                            .addComponent(jRBChegada))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFTChegadaVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFTSaidaVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBSimulacao)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBFaltasSem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFSemanas, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jFTSemanasVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jlNomeAlerta)
                        .addGap(4, 4, 4)
                        .addComponent(jTFNomeAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jBAlerta)
                        .addGap(6, 6, 6)
                        .addComponent(jBRelatorio)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBAluno)
                            .addComponent(jRBTurma)
                            .addComponent(jRBCurso))
                        .addGap(2, 2, 2)
                        .addComponent(jTFIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFTPeriodo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLAux))
                            .addComponent(jFTPeriodo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBFaltasCon)
                            .addComponent(jFTFaltasCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBFaltasInt)
                            .addComponent(jFTFaltasInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBFaltasSem)
                            .addComponent(jTFSemanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTSemanasVezes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBChegada)
                            .addComponent(jFTChegadaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTChegadaVezes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBSaida)
                            .addComponent(jFTSaidaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTSaidaVezes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBSimulacao)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jlNomeAlerta))
                            .addComponent(jTFNomeAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCriar)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRelatorioActionPerformed
        this.jRBAluno.setEnabled(true);
        this.jBAlerta.setEnabled(false);
        this.jBVoltar.setEnabled(true);

    }//GEN-LAST:event_jBRelatorioActionPerformed

    private void jRBAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBAlunoActionPerformed
        this.jTFIdentificacao.setEnabled(true);
    }//GEN-LAST:event_jRBAlunoActionPerformed

    private void jRBTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBTurmaActionPerformed
        this.jTFIdentificacao.setEnabled(true);
    }//GEN-LAST:event_jRBTurmaActionPerformed

    private void jRBCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCursoActionPerformed
        this.jTFIdentificacao.setEnabled(true);
    }//GEN-LAST:event_jRBCursoActionPerformed

    private void jTFIdentificacaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFIdentificacaoKeyReleased
        this.idPreenchido(jTFIdentificacao.getText().toUpperCase());


    }//GEN-LAST:event_jTFIdentificacaoKeyReleased

    private void jTFIdentificacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFIdentificacaoMouseClicked
        jTFIdentificacao.setText("");
        jTFIdentificacao.setForeground(Color.BLACK);


    }//GEN-LAST:event_jTFIdentificacaoMouseClicked

    private void jFTPeriodo2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTPeriodo2KeyReleased

        if (this.jTFIdentificacao.getText().length() > 0) {
            this.jRBChegada.setEnabled(true);
            this.jRBFaltasCon.setEnabled(true);
            this.jRBFaltasSem.setEnabled(true);
            this.jRBFaltasInt.setEnabled(true);
            this.jRBSaida.setEnabled(true);
        }
    }//GEN-LAST:event_jFTPeriodo2KeyReleased

    private void jRBFaltasConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBFaltasConActionPerformed
        this.verificaTipos();
    }//GEN-LAST:event_jRBFaltasConActionPerformed

    private void jRBFaltasIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBFaltasIntActionPerformed
        this.verificaTipos();
    }//GEN-LAST:event_jRBFaltasIntActionPerformed

    private void jRBChegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBChegadaActionPerformed
        this.verificaTipos();
    }//GEN-LAST:event_jRBChegadaActionPerformed

    private void jRBSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSaidaActionPerformed
        this.verificaTipos();
    }//GEN-LAST:event_jRBSaidaActionPerformed

    private void jBCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCriarActionPerformed

        if (this.jBRelatorio.isEnabled()) {
            this.periodo();
            if (this.jRBFaltasInt.isSelected()) {
                control = new ControleRelatorio(this.jTFIdentificacao, this.jFTFaltasInt, this.c1, this.c2);
                control.faltasInt();
            }
            if (this.jRBFaltasCon.isSelected()) {
                control = new ControleRelatorio(this.jTFIdentificacao, this.jFTFaltasCon, this.c1, this.c2);
                control.faltasCon();
            }
            if (this.jRBSaida.isSelected()) {
                control = new ControleRelatorio(this.jTFIdentificacao, this.jFTSaidaMin,
                        this.jFTSaidaVezes, this.c1, this.c2);
                control.saidaAntecipada();
            }
            if (this.jRBChegada.isSelected()) {
                control = new ControleRelatorio(this.jTFIdentificacao, this.jFTChegadaMin,
                        this.jFTChegadaVezes, this.c1, this.c2);
                control.chegadaTardia();
            }
            if (this.jRBFaltasSem.isSelected()) {
                control = new ControleRelatorio(this.jTFIdentificacao, this.jFTSemanasVezes, this.jTFSemanas,
                        this.c1, this.c2);
                control.faltasSemana();
            }

        } else {
            if (this.jRBChegada.isSelected()) {
                Calendar data = Calendar.getInstance();
                Alerta c = new Alerta(this.jTFIdentificacao.getText().toUpperCase(), data, this.jFTChegadaVezes.getText(),
                        this.jTFNomeAlerta.getText(), "1", this.jFTChegadaMin.getText());
                Bancos esc = new EscreveAlerta(c);
                esc.modificar();

            }

            if (this.jRBSaida.isSelected()) {
                Calendar data = Calendar.getInstance();
                Alerta c = new Alerta(this.jTFIdentificacao.getText().toUpperCase(), data, this.jFTSaidaVezes.getText(),
                        this.jTFNomeAlerta.getText(), "2", this.jFTSaidaMin.getText());
                Bancos esc = new EscreveAlerta(c);
                esc.modificar();

            }
        }
        this.limpaCampos();
        // this.jBCriar.setEnabled(false);
    }//GEN-LAST:event_jBCriarActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        this.limpaCampos();
        this.jBAlerta.setEnabled(true);
        this.jBRelatorio.setEnabled(true);
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jFTChegadaMinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTChegadaMinKeyReleased
        if (this.jFTChegadaMin.getText().length() > 0) {
            this.jFTChegadaVezes.setEnabled(true);
        } else {
            this.jFTChegadaVezes.setEnabled(false);
        }
    }//GEN-LAST:event_jFTChegadaMinKeyReleased

    private void jFTSaidaMinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTSaidaMinKeyReleased
        if (this.jFTSaidaMin.getText().length() > 0) {
            this.jFTSaidaVezes.setEnabled(true);
        } else {
            this.jFTSaidaVezes.setEnabled(false);

        }    }//GEN-LAST:event_jFTSaidaMinKeyReleased

    private void jFTFaltasIntKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTFaltasIntKeyReleased
        if (this.jFTFaltasInt.getText().length() > 0 && this.jBRelatorio.isEnabled() == true) {
            this.jBCriar.setEnabled(true);
        } else if (this.jFTFaltasInt.getText().length() > 0) {
            this.jTFNomeAlerta.setEnabled(true);
            this.jlNomeAlerta.setEnabled(true);
        } else {
            this.jTFNomeAlerta.setEnabled(false);
            this.jlNomeAlerta.setEnabled(false);
            this.jBCriar.setEnabled(false);

        }
    }//GEN-LAST:event_jFTFaltasIntKeyReleased

    private void jFTChegadaVezesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTChegadaVezesKeyReleased
        if (this.jFTChegadaVezes.getText().length() > 0 && this.jBRelatorio.isEnabled() == true) {
            this.jBCriar.setEnabled(true);
        } else if (this.jFTChegadaVezes.getText().length() > 0) {
            this.jTFNomeAlerta.setEnabled(true);
            this.jlNomeAlerta.setEnabled(true);
        } else {
            this.jTFNomeAlerta.setEnabled(false);
            this.jlNomeAlerta.setEnabled(false);
            this.jBCriar.setEnabled(false);

        }
    }//GEN-LAST:event_jFTChegadaVezesKeyReleased

    private void jFTSaidaVezesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTSaidaVezesKeyReleased
        if (this.jFTSaidaVezes.getText().length() > 0 && this.jBRelatorio.isEnabled() == true) {
            this.jBCriar.setEnabled(true);
        } else if (this.jFTSaidaVezes.getText().length() > 0) {
            this.jTFNomeAlerta.setEnabled(true);
            this.jlNomeAlerta.setEnabled(true);
        } else {
            this.jTFNomeAlerta.setEnabled(false);
            this.jlNomeAlerta.setEnabled(false);
            this.jBCriar.setEnabled(false);

        }
    }//GEN-LAST:event_jFTSaidaVezesKeyReleased

    private void jFTFaltasConKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTFaltasConKeyReleased
        if (this.jFTFaltasCon.getText().equals("  ")) {
            this.jBCriar.setEnabled(false);
        }

        if (this.jFTFaltasCon.getText().length() > 0 && this.jBRelatorio.isEnabled() == true) {
            this.jBCriar.setEnabled(true);
        } else if (this.jFTFaltasInt.getText().length() > 0) {
            this.jTFNomeAlerta.setEnabled(true);
            this.jlNomeAlerta.setEnabled(true);
        } else {
            this.jTFNomeAlerta.setEnabled(false);
            this.jlNomeAlerta.setEnabled(false);

        }
    }//GEN-LAST:event_jFTFaltasConKeyReleased

    private void jBAlertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlertaActionPerformed
        this.jRBAluno.setEnabled(true);
        this.jBSimulacao.setEnabled(true);
        this.jBRelatorio.setEnabled(false);
        this.jBVoltar.setEnabled(true);    }//GEN-LAST:event_jBAlertaActionPerformed

    private void jTFNomeAlertaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNomeAlertaKeyReleased
        this.jBCriar.setEnabled(true);
    }//GEN-LAST:event_jTFNomeAlertaKeyReleased

    private void jRBFaltasSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBFaltasSemActionPerformed
        this.verificaTipos();
    }//GEN-LAST:event_jRBFaltasSemActionPerformed

    private void jTFSemanasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSemanasKeyReleased
        String diaSema = this.jTFSemanas.getText().toUpperCase();
        if (diaSema.equals("SEGUNDA-FEIRA") || diaSema.equals("TERÇA-FEIRA") || diaSema.equals("QUARTA-FEIRA")
                || diaSema.equals("QUINTA-FEIRA") || diaSema.equals("SEXTA-FEIRA")) {
            this.jFTSemanasVezes.setEnabled(true);
        } else {
            this.jFTSemanasVezes.setEnabled(false);
        }


    }//GEN-LAST:event_jTFSemanasKeyReleased

    private void jFTSemanasVezesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFTSemanasVezesKeyReleased
        if (this.jFTSemanasVezes.getText().length() > 0 && this.jBRelatorio.isEnabled() == true) {
            this.jBCriar.setEnabled(true);
        } else if (this.jFTSemanasVezes.getText().length() > 0) {
            this.jTFNomeAlerta.setEnabled(true);
            this.jlNomeAlerta.setEnabled(true);
        } else {
            this.jTFNomeAlerta.setEnabled(false);
            this.jlNomeAlerta.setEnabled(false);
            this.jBCriar.setEnabled(false);

        }
    }//GEN-LAST:event_jFTSemanasVezesKeyReleased

    private void jTFSemanasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFSemanasMouseClicked
        jTFSemanas.setText("");
        jTFSemanas.setForeground(Color.BLACK);
    }//GEN-LAST:event_jTFSemanasMouseClicked

    private void jBSimulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSimulacaoActionPerformed
        Controle g = new ControleAlerta();
        g.chegadaTardia();
        g.saidaAntecipada();

    }//GEN-LAST:event_jBSimulacaoActionPerformed
    /**
     * método que define os objetos do tipo Calendar que definem o periodo dos
     * relatorios
     */
    private void periodo() {
        if (this.jBRelatorio.isEnabled()) {
            this.c1 = Calendar.getInstance();
            this.c2 = Calendar.getInstance();
            String p1[] = jFTPeriodo1.getText().split("/");
            String p2[] = jFTPeriodo2.getText().split("/");

            c1.set(Calendar.YEAR, Integer.parseInt(p1[2]));
            c1.set(Calendar.MONTH, Integer.parseInt(p1[1]) - 1);
            c1.set(Calendar.DAY_OF_MONTH, Integer.parseInt(p1[0]));
            c2.set(Calendar.YEAR, Integer.parseInt(p2[2]));

            c2.set(Calendar.MONTH, Integer.parseInt(p2[1]) - 1);
            c2.set(Calendar.DAY_OF_MONTH, Integer.parseInt(p2[0]));

        }
    }

    /**
     * método que verifica se o aluno que foi informado existe no banco de dados
     * ou não
     *
     * @param texto = nome do aluno
     */
    private void idPreenchido(String texto) {
        Bancos d = new Academico(texto);

        d.gerar();
        d.consultar();
        if (this.jBRelatorio.isEnabled() == true && d.autenticado()) {

            this.jFTPeriodo1.setEnabled(true);
            this.jFTPeriodo2.setEnabled(true);
            this.jLAux.setEnabled(true);
        } else if (d.autenticado()) {
            this.jRBChegada.setEnabled(true);
            this.jRBFaltasCon.setEnabled(false);
            this.jRBFaltasSem.setEnabled(false);
            this.jRBFaltasInt.setEnabled(false);
            this.jRBSaida.setEnabled(true);
        } else {
            this.jFTPeriodo1.setEnabled(false);
            this.jFTPeriodo2.setEnabled(false);
            this.jLAux.setEnabled(false);
            this.jRBChegada.setEnabled(false);
            this.jRBFaltasCon.setEnabled(false);
            this.jRBFaltasSem.setEnabled(false);
            this.jRBFaltasInt.setEnabled(false);
            this.jRBSaida.setEnabled(false);

        }

    }

    /**
     * método que verifica qual tipo de filtro foi selecionado pelo usuário
     */
    private void verificaTipos() {
        if (this.jRBFaltasCon.isSelected()) {
            this.jFTFaltasCon.setEnabled(true);

        } else {
            this.jFTFaltasCon.setEnabled(false);
            this.jFTFaltasCon.setText("");
        }

        if (this.jRBFaltasInt.isSelected()) {
            this.jFTFaltasInt.setEnabled(true);
        } else {
            this.jFTFaltasInt.setEnabled(false);
            this.jFTFaltasInt.setText("");
        }

        if (this.jRBChegada.isSelected()) {
            this.jFTChegadaMin.setEnabled(true);
        } else {
            this.jFTChegadaMin.setEnabled(false);
            this.jFTChegadaVezes.setEnabled(false);
            this.jFTChegadaMin.setText("");
            this.jFTChegadaVezes.setText("");
        }
        if (this.jRBFaltasSem.isSelected()) {
            this.jTFSemanas.setEnabled(true);
        } else {
            this.jTFSemanas.setEnabled(false);
            this.jFTSemanasVezes.setEnabled(false);
            this.jTFSemanas.setText("");
            this.jFTSemanasVezes.setText("");

        }
        if (this.jRBSaida.isSelected()) {
            this.jFTSaidaMin.setEnabled(true);
        } else {
            this.jFTSaidaMin.setEnabled(false);
            this.jFTSaidaVezes.setEnabled(false);
            this.jFTSaidaMin.setText("");
            this.jFTSaidaVezes.setText("");
        }
    }

    /**
     * método para zerar os campos
     */
    private void limpaCampos() {
        this.jRBAluno.setEnabled(false);
        this.jRBCurso.setEnabled(false);
        this.jRBTurma.setEnabled(false);
        this.bGMonitora.clearSelection();
        this.bGTipos.clearSelection();
        this.jFTPeriodo1.setEnabled(false);
        this.jFTPeriodo2.setEnabled(false);
        this.jLAux.setEnabled(false);
        this.jRBChegada.setEnabled(false);
        this.jRBFaltasCon.setEnabled(false);
        this.jRBFaltasSem.setEnabled(false);
        this.jRBFaltasInt.setEnabled(false);
        this.jRBSaida.setEnabled(false);
        this.jTFIdentificacao.setText("");
        this.jTFIdentificacao.setEnabled(false);
        this.jBCriar.setEnabled(false);
        this.jTFNomeAlerta.setText("");
        this.jTFNomeAlerta.setEnabled(false);
        this.jFTPeriodo1.setText("");
        this.jFTPeriodo2.setText("");
        this.verificaTipos();
        this.jBAlerta.setEnabled(true);
        this.jBRelatorio.setEnabled(true);
        this.jBVoltar.setEnabled(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGMonitora;
    private javax.swing.ButtonGroup bGTipos;
    private javax.swing.JButton jBAlerta;
    private javax.swing.JButton jBCriar;
    private javax.swing.JButton jBExcluirTab;
    private javax.swing.JButton jBRelatorio;
    private javax.swing.JButton jBSimulacao;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JFormattedTextField jFTChegadaMin;
    private javax.swing.JFormattedTextField jFTChegadaVezes;
    private javax.swing.JFormattedTextField jFTFaltasCon;
    private javax.swing.JFormattedTextField jFTFaltasInt;
    private javax.swing.JFormattedTextField jFTPeriodo1;
    private javax.swing.JFormattedTextField jFTPeriodo2;
    private javax.swing.JFormattedTextField jFTSaidaMin;
    private javax.swing.JFormattedTextField jFTSaidaVezes;
    private javax.swing.JFormattedTextField jFTSemanasVezes;
    private javax.swing.JLabel jLAux;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBAluno;
    private javax.swing.JRadioButton jRBChegada;
    private javax.swing.JRadioButton jRBCurso;
    private javax.swing.JRadioButton jRBFaltasCon;
    private javax.swing.JRadioButton jRBFaltasInt;
    private javax.swing.JRadioButton jRBFaltasSem;
    private javax.swing.JRadioButton jRBSaida;
    private javax.swing.JRadioButton jRBTurma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFIdentificacao;
    private javax.swing.JTextField jTFNomeAlerta;
    private javax.swing.JTextField jTFSemanas;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlNomeAlerta;
    // End of variables declaration//GEN-END:variables
}
